### ISSUE TITLE
Unable to edit relatives confirm button unclickable and save form not working 

### ISSUE THREAD

**Issue by aprilcurrier** [openmrs-indianaems/openmrs-indianaems-config#11]
![image](https://user-images.githubusercontent.com/58441201/79791807-e6ef0080-831b-11ea-91ec-fe8439fb7159.png)

![image](https://user-images.githubusercontent.com/58441201/79791769-da6aa800-831b-11ea-9bed-0d6ccf3d00ee.png)

**Comment by aprilcurrier** [comment]
This is occurring when trying to later edit registration information

**Comment by aprilcurrier** [comment]
![image](https://user-images.githubusercontent.com/58441201/79792005-303f5000-831c-11ea-92b1-320ac36e43c1.png)

**Comment by bmamlin** [comment]
Relationships app was stopped, which should resolve this problem.
