### ISSUE TITLE
Unable to add attachments when no visit is opened

### ISSUE THREAD

**Issue by aprilcurrier** [openmrs-indianaems/openmrs-indianaems-config#12]
There is a lack of error message. Below is what shows when a visit is not currently open/active when a user tries to add an attachment

![image](https://user-images.githubusercontent.com/58441201/79792734-67623100-831d-11ea-887c-2cf08cddb605.png)

![image](https://user-images.githubusercontent.com/58441201/79792518-0b97a800-831d-11ea-8d9f-ee35d48ae7fd.png)

After the user clicks okay on the error message 

![image](https://user-images.githubusercontent.com/58441201/79792770-7ba62e00-831d-11ea-90d1-782db8e5665f.png)

**Comment by aprilcurrier** [comment]
In contrast to what a user sees when a visit is active 

![image](https://user-images.githubusercontent.com/58441201/79792678-4ef21680-831d-11ea-9fe0-390a250948ed.png)

**Comment by maurya** [comment]
We are not supporting attachment feature per past conversations and comparison with dev box @jonathandick 

Also, stopped appointment scheduling feature as that is also a feature we are not supporting for this implementation

please reopen if this is a required feature.
