### ISSUE TITLE
Fix answers to "Tested for SARS-CoV-2"

### ISSUE THREAD

**Issue by bmamlin** [openmrs-indianaems/openmrs-indianaems-config#13]
Answers (at least what the user sees on the form) for "Tested for SARS-CoV-2" should be changed from "+" and "-" to "Yes" and "No"

![image](https://user-images.githubusercontent.com/860834/79817378-5a603480-8353-11ea-87cf-2c8b567e490f.png)

**Comment by jamlung-ri** [comment]
This change is done
