### ISSUE TITLE
Fix answers for "SARS-CoV-2 result"

### ISSUE THREAD

**Issue by bmamlin** [openmrs-indianaems/openmrs-indianaems-config#14]
The answers for "SARS-CoV-2 result" (at for the user) should be changed from "+" and "-" to the words "Positive" and "Negative" to reduce the chance of erroneous data entry.

![image](https://user-images.githubusercontent.com/860834/79817507-a14e2a00-8353-11ea-8355-f254b6a35e25.png)

**Comment by jamlung-ri** [comment]
This change is done
