### ISSUE TITLE
Vitals - Temperature Max in Vitals

### ISSUE THREAD

**Issue by jburnsthomas** [openmrs-indianaems/openmrs-indianaems-config#18]
VITALS - Temperature maxed out at 45 degrees C, want to increase the max to 50 degrees C

**Comment by jamlung-ri** [comment]
@maurya Is this something that will need to be done manually in the concept dictionary? I don't see this concept in the Initializer CSV.

**Comment by jburnsthomas** [comment]
@maurya do you think we could add this issue to this existing OMRS one - https://issues.openmrs.org/browse/AC-572?jql=text%20~%20%22temperature%22

**Comment by maurya** [comment]
@jburnsthomas No, that ticket is the android client issue, but I don't think this can be fixed in the android client. We can either move this issue into reference application issues or create a reference application issue and combine/reference this issue,

**Comment by jburnsthomas** [comment]
Did not find as an existing OMRS issue so added ticket - https://issues.openmrs.org/projects/RA/issues/RA-1751
