### ISSUE TITLE
VITALS - Route of Temp Taken

### ISSUE THREAD

**Issue by jburnsthomas** [openmrs-indianaems/openmrs-indianaems-config#19]
VITALS - Add the route of temperature taken (oral, axillary, etc.)

**Comment by jamlung-ri** [comment]
I am going to take a stab at this one, though I generally have not done the Vitals form before. I might have to ask for help, if I end up having trouble.

**Comment by terrycullen** [comment]
Joe, did they indicate what options are needed ( oral, axillary, ? Tympanic (in the ear)); I am assuming that we are not taking rectal temps but that would also be a usual option

**Comment by jamlung-ri** [comment]
CIEL does not have this concept, it appears, but [LOINC has a concept for this.](https://loinc.org/8327-9/) @terrycullen Should I use these as the potential input options?

LOINC options include:

- Axillary 
- Oral
- Ear 
- Tympanic membrane 
- Temporal artery (forehead)
- Rectal
- Urinary bladder
- Nasal 
- Nasopharyngeal 
- Finger 
- Toe

**Comment by terrycullen** [comment]
use axillary, oral, ear, temporal artery (though maybe call it forehead on the form) and rectal
I wouldn't include the others ( I dont know what the difference is between ear and Tympanic membrane!!--- I would just use one of these; probably ear...)

**Comment by jamlung-ri** [comment]
I have also added this concept to the Initializer CSV file which is now up to date in GitHub. It has not been incorporated into the Vitals form, however. Unless otherwise instructed, I do not plan to make any changes into the Test environment. Leaving this ticket open until that is done.

**Comment by jburnsthomas** [comment]
@bmamlin and @maurya can these changes be made in the test environment? Or is there another next step.

**Comment by jburnsthomas** [comment]
Did not find as an existing OMRS issue so added ticket - https://issues.openmrs.org/projects/RA/issues/RA-1750
