### ISSUE TITLE
COVID - Workflow testing - CANNOT SAVE COVID FORM

### ISSUE THREAD

**Issue by jennifershivers** [openmrs-indianaems/openmrs-indianaems-config#2]
used account Joedoc password Admin123
1.  Regestered patient w w w
2. Started visit 
3. Logged vitals 
4.  Tried COVID form 
Covid form will not save 

- clicked studnet 
- clicked oxygen 
- clicked whatever the save button is called 

Error
<img width="398" alt="Screen Shot 2020-04-06 at 9 10 52 AM" src="https://user-images.githubusercontent.com/13437212/78562021-ad2fdd00-77e6-11ea-848d-bb274c3354e8.png">

**Comment by jennifershivers** [comment]
We cannot test the COVID form until this part is working.

**Comment by jamlung-ri** [comment]
This has been fixed by adding the Date, Location, and Provider fields to the form. @jennifershivers please test and close this issue if fixed on your end.
