### ISSUE TITLE
VITALS - Blood Pressure Input

### ISSUE THREAD

**Issue by jburnsthomas** [openmrs-indianaems/openmrs-indianaems-config#21]
VITALS - Blood pressure - suggested that P for Palp(?) can be an input for diastolic

- Idea is that in a noisy setting, hard to auscultate and hear the bottom end of BP, so blood pressure is 140 / Palp (more common outside of hospital)

- Often time documented that way because it’s the only realistic way

**Comment by jamlung-ri** [comment]
I can try to just include a checkbox for Palp in the electronic form. If this does not work, we can explore other options.

**Comment by jburnsthomas** [comment]
Did not find as an existing OMRS issue so added ticket - https://issues.openmrs.org/projects/RA/issues/RA-1748
