### ISSUE TITLE
COVID FORM - Exam symptoms yes or no

### ISSUE THREAD

**Issue by jburnsthomas** [openmrs-indianaems/openmrs-indianaems-config#24]
COVID Form - Can select yes and no for exam symptom findings (Known)

- Boxes were also dark, hard to know which were clicked and not clicked

**Comment by jamlung-ri** [comment]
Since ticket #3 already focuses on this, this ticket should focus on the form boxes being dark. That said, I have no clue how to change styling for check boxes.

**Comment by maurya** [comment]
Could not replicate
