### ISSUE TITLE
REGISTRATION - Unidentified Patient

### ISSUE THREAD

**Issue by jburnsthomas** [openmrs-indianaems/openmrs-indianaems-config#25]
REGISTRATION - If patient were unidentified (mass casualty, for example) - Automated unknown system (Alpha, Bravo, Charlie)

**Comment by bmamlin** [comment]
I don't know what "(Alpha, Bravo, Charlie)" means... maybe it's an Indy EMS thing?

The Reference Application comes with an ability to register unidentified patients:
![image](https://user-images.githubusercontent.com/860834/80836152-26420a80-8bc2-11ea-909f-0de3a88360c8.png)
It's as simple as (1) check the "Unidentified patient" box, (2) supply a gender, and (3) confirm. The patient is registered as "Unknown Unknown" and is given a medical record number that can be used to access the patient's record in the system.
