### ISSUE TITLE
COVID form - Can check both fever + and Fever -

### ISSUE THREAD

**Issue by jennifershivers** [openmrs-indianaems/openmrs-indianaems-config#3]
<img width="535" alt="Screen Shot 2020-04-06 at 9 16 36 AM" src="https://user-images.githubusercontent.com/13437212/78562475-6bebfd00-77e7-11ea-98de-385face4aba2.png">

**Comment by kepishelf** [comment]
fyi - all items in the section "Current Symptoms:"  and "Physical Exam:" behave this way-- users Can select both +  and -

**Comment by jennifershivers** [comment]
Is that how we intend the system to work?

**Comment by jamlung-ri** [comment]
Nope. I think these should be changed from checkboxes to radio buttons. This is something I can do.

**Comment by terrycullen** [comment]
no; there is one answer

**Comment by bmamlin** [comment]
This will take a little more than form edits. It will probably need some of the JavaScript tricks as described on [this wiki page](https://wiki.openmrs.org/x/7g4z).

**Comment by jamlung-ri** [comment]
I forgot to update this, but Burke is correct. We will need Javascript to make this work, and I don't think we can support that right now.

**Comment by bmamlin** [comment]
I'd suggest we close this for now as "won't fix". We know what is needed to implement the feature, but don't need to implement it until/unless the form is going to be used or piloted.

**Comment by jburnsthomas** [comment]
@bmamlin if we do a trial under the SAEMF grant would this need to be fixed prior to that?

**Comment by bmamlin** [comment]
Yes.
