### ISSUE TITLE
UI - Please delete "admit to inpatient"

### ISSUE THREAD

**Issue by jennifershivers** [openmrs-indianaems/openmrs-indianaems-config#4]
Can we delete admit to inpatient on both of these forms
<img width="787" alt="Screen Shot 2020-04-06 at 9 31 21 AM" src="https://user-images.githubusercontent.com/13437212/78563803-8921cb00-77e9-11ea-8972-d158e1d11745.png">

<img width="788" alt="Screen Shot 2020-04-06 at 9 43 47 AM" src="https://user-images.githubusercontent.com/13437212/78564956-31845f00-77eb-11ea-80a8-4b03c850365f.png">

**Comment by terrycullen** [comment]
I am not sure; some people may to to the hospital as direct admit
we probably need to ask Nancy; I will do that

**Comment by jamlung-ri** [comment]
Nancy confirmed that this can be eliminated.

**Comment by jennifershivers** [comment]
Agree with Joe - we agreed that it needs to be deleted - it is covered on the COVID form and can be covered in the non-covid note

**Comment by terrycullen** [comment]
yes; I had asked Nancy and copied Joe; in cases like this, I think that the decision is with the SME who is using the form-- so it is good that we all agree!! )

**Comment by bmamlin** [comment]
Unfortunately, this feature appears to be hardcoded into the reference application module. Assuming we're going to have to fork the module to override the vitals form, we can include this change in our fork.

**Comment by jennifershivers** [comment]
OK - DEcision leave in application for now
