### ISSUE TITLE
Vitals - Height and weight are still metric

### ISSUE THREAD

**Issue by jennifershivers** [openmrs-indianaems/openmrs-indianaems-config#5]
Change height and weight on vitals to non-metric measurements
<img width="325" alt="Screen Shot 2020-04-06 at 9 39 09 AM" src="https://user-images.githubusercontent.com/13437212/78564564-9e4b2980-77ea-11ea-9fc1-5248ce96ec3e.png">

**Comment by jburnsthomas** [comment]
Did not find as an existing OMRS issue so added ticket - https://issues.openmrs.org/browse/RA-1754
