### ISSUE TITLE
Pt registration error

### ISSUE THREAD

**Issue by jennifershivers** [openmrs-indianaems/openmrs-indianaems-config#6]
Just trying to register a patient to see if some of the training works.  
<img width="778" alt="Screen Shot 2020-04-07 at 2 43 31 PM" src="https://user-images.githubusercontent.com/13437212/78707190-48f04480-78de-11ea-89aa-13f147f32eb3.png">

Tried to fill in more data to see if new data was required for IHIE 
<img width="1070" alt="Screen Shot 2020-04-07 at 2 48 45 PM" src="https://user-images.githubusercontent.com/13437212/78707691-f400fe00-78de-11ea-9046-66f5bdc61872.png">

**Comment by maurya** [comment]
I was able to register a patient in our environment. @jennifershivers, Is this an ADT issue we are looking into? or can we close this
