### ISSUE TITLE
Password Force change not working 

### ISSUE THREAD

**Issue by aprilcurrier** [openmrs-indianaems/openmrs-indianaems-config#9]
![image](https://user-images.githubusercontent.com/58441201/79789930-f751ac00-8318-11ea-9d8c-f9b59326e131.png)

![image](https://user-images.githubusercontent.com/58441201/79789906-ed2fad80-8318-11ea-9c66-5d2d1f3c9204.png)

**Comment by aprilcurrier** [comment]
When logging in to the newly created account the user is to prompted to choose a new password

**Comment by maurya** [comment]
Force password change only shows up if the person is navigating to the legacy UI, the Reference UI functions are not blocked. This behaviour is the same in Demo server. 
This is a Refapp-change

**Comment by jburnsthomas** [comment]
Did not find as an existing OMRS issue so added ticket - https://issues.openmrs.org/browse/RA-1753
